const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vscode = require('vscode');
const core = require('../../packages/core/dist');
const wait = () => new Promise(resolve => setTimeout(resolve, 400));
exports.run = async () => {
  const extension = vscode.extensions.getExtension('margin-local.margin');
  assert.ok(extension, 'development extension available');
  const api = await extension.activate(); await vscode.commands.executeCommand('margin.refresh');
  const info = api.inspect(); assert.equal(info.threads, 1); assert.equal(info.items, 1);
  const root = vscode.workspace.workspaceFolders[0].uri.fsPath;
  const session = core.loadSession(root, info.session), comment = session.comments[0];
  const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(path.join(root,'draft.md')));
  await vscode.window.showTextDocument(doc);
  const disk = fs.readFileSync(doc.uri.fsPath);
  const originalStart = api.inspect().attachments[0].start;
  // Source editing occurs ONLY in this disposable test fixture, as a simulated user.
  const edit = new vscode.WorkspaceEdit(); edit.insert(doc.uri, new vscode.Position(0,0), 'A user-added preface.\n\n');
  assert.equal(await vscode.workspace.applyEdit(edit), true); await wait();
  assert.equal(doc.isDirty, true);
  assert.equal(api.inspect().attachments[0].start, doc.getText().indexOf(comment.anchor.quote));
  assert.ok(api.inspect().attachments[0].start > originalStart);
  assert.equal(api.inspect().attachments[0].unsaved, true);
  await vscode.commands.executeCommand('margin.reply', {id:comment.id, text:'Local test reply'});
  for (const [command, status] of [['margin.resolve','resolved'],['margin.dismiss','dismissed']]) {
    await vscode.commands.executeCommand('margin.reopen', {id:comment.id});
    await vscode.commands.executeCommand('margin.open', {id:comment.id});
    assert.equal(api.inspect().threadStates[comment.id], vscode.CommentThreadCollapsibleState.Expanded);
    await vscode.commands.executeCommand(command, {id:comment.id});
    assert.equal(api.inspect().threadStates[comment.id], vscode.CommentThreadCollapsibleState.Collapsed, `${command} closes the editor thread`);
    await vscode.commands.executeCommand('margin.refresh'); await wait();
    assert.equal(api.inspect().threadStates[comment.id], vscode.CommentThreadCollapsibleState.Collapsed, 'refresh preserves the collapsed thread');
    assert.equal(core.loadState(root,session).state.comments[comment.id].status,status);
    assert.equal(api.inspect().items,1,'closed discussions remain in the review tree');
    await vscode.commands.executeCommand('margin.open', {id:comment.id});
    assert.equal(api.inspect().threadStates[comment.id], vscode.CommentThreadCollapsibleState.Expanded, 'closed discussions can still be inspected');
  }
  await vscode.commands.executeCommand('margin.resolve', {id:comment.id});
  const state = core.loadState(root, session).state.comments[comment.id];
  assert.equal(state.status, 'resolved'); assert.equal(state.replies[0].body, 'Local test reply');
  await vscode.commands.executeCommand('margin.original', {id:comment.id});
  assert.equal(vscode.window.activeTextEditor.document.uri.scheme, 'margin');
  assert.equal(vscode.window.activeTextEditor.document.getText(), core.snapshotText(root, session.snapshot_id, 'draft.md'));
  await vscode.commands.executeCommand('margin.compare', {id:comment.id});
  // Deleted targets remain discoverable; manual reattachment preserves the original evidence.
  const current = api.inspect().attachments[0];
  const deletion = new vscode.WorkspaceEdit(); deletion.delete(doc.uri,new vscode.Range(doc.positionAt(current.start),doc.positionAt(current.end)));
  await vscode.workspace.applyEdit(deletion); await wait();
  assert.equal(api.inspect().attachments[0].status,'unanchored');
  assert.equal(api.inspect().threads,0);assert.equal(api.inspect().items,1);
  await vscode.commands.executeCommand('margin.open',{id:comment.id});assert.equal(vscode.window.activeTextEditor.document.uri.scheme,'margin');
  const editor=await vscode.window.showTextDocument(doc);
  editor.selection=new vscode.Selection(doc.positionAt(0),doc.positionAt(20));
  await vscode.commands.executeCommand('margin.reattach',{id:comment.id});await vscode.commands.executeCommand('margin.refresh');
  assert.equal(api.inspect().attachments[0].status,'attached');assert.equal(api.inspect().threads,1);
  const override=core.loadState(root,session).state.comments[comment.id].override;
  assert.equal(override.quote,doc.getText().slice(0,20));assert.equal(override.unsaved,true);
  assert.deepEqual(core.loadSession(root,session.id).comments[0].anchor,comment.anchor);
  await vscode.commands.executeCommand('margin.letter');
  assert.match(vscode.window.activeTextEditor.document.getText(), /Deterministic offline/);
  assert.deepEqual(fs.readFileSync(doc.uri.fsPath), disk, 'Margin did not save the dirty draft');
  await require('./navigation.cjs').run(api,root,session);
  console.log('Margin Extension Development Host smoke passed: threads, automatic collapse on resolve/dismiss, tree, dirty-buffer mapping, local state, detached targets, manual reattachment, original/current comparison, editorial letter.');
};
